Mvc inversify repo branch
YSherbini/gym-event-manager pull request #1
Opened 2023-12-28 13:46 UTC by YSherbini

2024-01-01 12:39 UTC, mismailk commented
1. Add more spaces between lines to make it more readable.
2. Remove unnecessary try catches blocks.

2024-01-02 12:09 UTC, mismailk requested changes

2024-01-02 12:09 UTC, mismailk commented on src/repositories/CategoryRepository.ts
> +        try {
No need for try and catch

2024-01-02 12:09 UTC, mismailk commented on src/controllers/CategoryController.ts
> +        try {
No need for try catch

2024-01-02 12:09 UTC, mismailk commented on src/controllers/CategoryController.ts
> +@controller('/categories')
You can add auth middleware within @controller to be applied for all routes in the class

2024-01-02 12:09 UTC, mismailk commented on src/interfaces/IQuery.ts
> +export interface IQuery {
Choose a meaningfull name for the interface as EventParams or EventQueryParams.

2024-01-02 12:09 UTC, mismailk commented on src/repositories/EventRepository.ts
> +        if (typeof name === 'string') {
What is the need for type checking you already define the type on IQuery interface

2024-01-02 12:09 UTC, mismailk commented on src/repositories/RegisterRepository.ts
> +                {
use $unwind to convert an array with one element to an object

2024-01-02 12:09 UTC, mismailk commented on src/controllers/TeamController.ts
> +            let team = await this.teamRepository.create({ name, categoryId, registerId, gymOwnerId, eventId: register.eventId });
You may receive eventId as a parameter in the request body

2024-01-02 12:09 UTC, mismailk commented on src/repositories/TeamRepository.ts
> +                dupTeams.teams.push(dupTeam);
You can simplify this more using object destructuring.

```suggestion
                const dupTeam = await this.create({...team.toObject(), _id: undefined});
                dupTeams.teams.push(dupTeam);
```

2024-01-02 12:09 UTC, mismailk commented on src/repositories/TeamRepository.ts
> +        return new Team(teamParams);
This isn't an async operation

2024-01-02 12:09 UTC, mismailk commented on src/repositories/TeamRepository.ts
> +        }
You can use Promise.all to run an asynchronous in parallel.

2024-01-02 12:09 UTC, mismailk commented on src/repositories/TeamRepository.ts
> +            sort[sortee] = order === 'desc' ? -1 : 1;
Don't use magic numbers or strings define an enum to inhance redability.

2024-01-04 19:08 UTC, YSherbini commented
I've implemented the requested changes and changed code to commonjs.

2024-06-27 11:14 UTC, closed without merging